spring.application.name=project

# 1. 서버 포트 설정
server.port=8282

# 2. DB 연결 설정 (HikariCP)
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.hikari.username=postgres
spring.datasource.hikari.password=1234


