spring.application.name=project

server.port=8282

spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/project
spring.datasource.hikari.username=project
spring.datasource.hikari.password=1234

spring.devtools.restart.enabled=false